// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.2
// source: broker.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BrokerClient is the client API for Broker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerClient interface {
	RedirectEngineer(ctx context.Context, in *EngineerRequest, opts ...grpc.CallOption) (*FulcrumAddress, error)
	RedirectCommander(ctx context.Context, in *CommanderRequest, opts ...grpc.CallOption) (*FulcrumAddress, error)
	ResolveConflict(ctx context.Context, in *ConflictRequest, opts ...grpc.CallOption) (*FulcrumAddress, error)
}

type brokerClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerClient(cc grpc.ClientConnInterface) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) RedirectEngineer(ctx context.Context, in *EngineerRequest, opts ...grpc.CallOption) (*FulcrumAddress, error) {
	out := new(FulcrumAddress)
	err := c.cc.Invoke(ctx, "/broker.Broker/RedirectEngineer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) RedirectCommander(ctx context.Context, in *CommanderRequest, opts ...grpc.CallOption) (*FulcrumAddress, error) {
	out := new(FulcrumAddress)
	err := c.cc.Invoke(ctx, "/broker.Broker/RedirectCommander", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) ResolveConflict(ctx context.Context, in *ConflictRequest, opts ...grpc.CallOption) (*FulcrumAddress, error) {
	out := new(FulcrumAddress)
	err := c.cc.Invoke(ctx, "/broker.Broker/ResolveConflict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServer is the server API for Broker service.
// All implementations must embed UnimplementedBrokerServer
// for forward compatibility
type BrokerServer interface {
	RedirectEngineer(context.Context, *EngineerRequest) (*FulcrumAddress, error)
	RedirectCommander(context.Context, *CommanderRequest) (*FulcrumAddress, error)
	ResolveConflict(context.Context, *ConflictRequest) (*FulcrumAddress, error)
	mustEmbedUnimplementedBrokerServer()
}

// UnimplementedBrokerServer must be embedded to have forward compatible implementations.
type UnimplementedBrokerServer struct {
}

func (UnimplementedBrokerServer) RedirectEngineer(context.Context, *EngineerRequest) (*FulcrumAddress, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedirectEngineer not implemented")
}
func (UnimplementedBrokerServer) RedirectCommander(context.Context, *CommanderRequest) (*FulcrumAddress, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedirectCommander not implemented")
}
func (UnimplementedBrokerServer) ResolveConflict(context.Context, *ConflictRequest) (*FulcrumAddress, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveConflict not implemented")
}
func (UnimplementedBrokerServer) mustEmbedUnimplementedBrokerServer() {}

// UnsafeBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServer will
// result in compilation errors.
type UnsafeBrokerServer interface {
	mustEmbedUnimplementedBrokerServer()
}

func RegisterBrokerServer(s grpc.ServiceRegistrar, srv BrokerServer) {
	s.RegisterService(&Broker_ServiceDesc, srv)
}

func _Broker_RedirectEngineer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EngineerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).RedirectEngineer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/broker.Broker/RedirectEngineer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).RedirectEngineer(ctx, req.(*EngineerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_RedirectCommander_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommanderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).RedirectCommander(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/broker.Broker/RedirectCommander",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).RedirectCommander(ctx, req.(*CommanderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_ResolveConflict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConflictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).ResolveConflict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/broker.Broker/ResolveConflict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).ResolveConflict(ctx, req.(*ConflictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Broker_ServiceDesc is the grpc.ServiceDesc for Broker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Broker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "broker.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RedirectEngineer",
			Handler:    _Broker_RedirectEngineer_Handler,
		},
		{
			MethodName: "RedirectCommander",
			Handler:    _Broker_RedirectCommander_Handler,
		},
		{
			MethodName: "ResolveConflict",
			Handler:    _Broker_ResolveConflict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "broker.proto",
}
